platform :ios, '10.0'

require_relative '../node_modules/@unimodules/core/podfile-macro'

# don't just copy and paste this, notice that the target names should align with what is already in your Podfile
target 'burner_native' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  
  use_unimodules!
  pod 'boost-for-react-native'
  pod 'EXCamera', :path => '../node_modules/expo-camera/ios'
  
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  target 'burner_nativeTests' do
    inherit! :search_paths
  end
  post_install do |installer|
    installer.pods_project.targets.each do |target|

      # The following is needed to ensure the "archive" step works in XCode.
      # It removes React & Yoga from the Pods project, as it is already included in the main project.
      # Without this, you'd see errors when you archive like:
      # "Multiple commands produce ... libReact.a"
      # "Multiple commands produce ... libyoga.a"

      targets_to_ignore = %w(React yoga)
      
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end

    end
  end
end