platform :ios, '10.0'

require_relative '../node_modules/@unimodules/core/podfile-macro'

# don't just copy and paste this, notice that the target names should align with what is already in your Podfile
target 'burner_native' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  
  use_unimodules!
  pod 'boost-for-react-native'
  pod 'EXCamera', :path => '../node_modules/expo-camera/ios'
  
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'burner_nativeTests' do
    inherit! :search_paths
  end
end